-- 记忆事实层（2026-09-18）：一条记忆 = 一个事实（subject 实体 + predicate 属性 + object 值）
-- 为什么：core/work 记忆是"一段话"，只能整条替换、检索只能靠字面；事实层让"改教室只改教室那条"
-- 和"按 subject 聚合着读"成立。向量列直接放 pgvector（`embedding vector(1024)`）。
--
-- 注意：`embedding` / `embedding_model` **不映射进 JPA 实体**——Hibernate 不认识 vector 类型，
-- 映射了会让 `ddl-auto: validate` 失败；这两列只由 JdbcTemplate 的 SQL 读写。

create extension if not exists vector;

create table if not exists memory_fact (
    id              bigint generated by default as identity primary key,
    user_id         varchar(128)  not null,
    subject         varchar(200)  not null,
    predicate       varchar(64)   not null,
    object          varchar(500)  not null,
    content         varchar(1000) not null,
    source          varchar(16)   not null,
    confidence      int           not null default 70,
    status          varchar(16)   not null,
    valid_from      timestamp(6),
    valid_to        timestamp(6),
    superseded_by   bigint,
    doc_media_id    bigint,
    keywords        varchar(500),
    embedding       vector(1024),
    embedding_model varchar(64),
    created_at      timestamp(6)  not null,
    updated_at      timestamp(6)  not null
);

create index if not exists idx_fact_user_status on memory_fact (user_id, status);
create index if not exists idx_fact_lookup on memory_fact (user_id, subject, predicate);
-- 余弦距离的 HNSW 索引（pgvector 0.5+ 支持；数据量小的时候也会自动走顺序扫描，不影响正确性）
create index if not exists idx_fact_embedding on memory_fact using hnsw (embedding vector_cosine_ops);
