-- 记忆分层合并（2026-09-18，用户决定：5 张表 → 3 张）
--
-- 背景：core / work / episode 三张表在"操作"上其实只有两条轴——
--   ① 要不要**每轮无条件注入**（原来只有 core 是这样）
--   ② 是不是**有槽位的当前值**（那是 memory_fact）或**原文证据**（那是 conversation_memory）
-- 实测这两层边界已经站不住：生产只有 19 行 episode，而 work 里大量行本身就是"经历"；
-- 所以把三张散文表合成一张 `memory`，用 `kind` 区分语义、`always_inject` 决定注入策略。
--
-- 合并后：
--   memory              —— 我对你的了解（一条一句话，有生命周期，按 always_inject 或相关性进提示词）
--   memory_fact         —— 会变的信息的当前值（有槽位，可精确改写）  【不动】
--   conversation_memory —— 我们当时说的原话（证据，只能遗忘）        【不动】
--
-- 老表**不删**：本次只搬数据（113 行），老表留作切削前的快照，回滚时可依靠它。
-- 等跑几天确认无误，再用单独的迁移删掉（那一步用户说了再执行）。
--
-- id 会撞车（三张表各自从 1 开始），而 core/work 有 superseded_by_id 自引用：
-- 所以先插 `legacy_id` 记下老 id，搬完用 (kind, legacy_id) 自连接回填引用，最后删掉这一列。
--
-- ⚠️ 必须先跑本迁移再部署新镜像：新实体映射 `memory` 表与 `memory_fact.embedding` 一样不映射向量列，
--    但表不存在会让 `ddl-auto: validate` 直接起不来。

create extension if not exists vector;

create table if not exists memory (
    id                  bigint generated by default as identity primary key,
    user_id             varchar(128) not null,
    kind                varchar(16)  not null,
    content             text         not null,
    title               varchar(200),
    category            varchar(32),
    always_inject       boolean      not null default false,
    status              varchar(32)  not null,
    importance          integer,
    confidence          integer,
    priority            integer,
    keywords            varchar(1000),
    source              varchar(32),
    source_type         varchar(32),
    source_message_ids  varchar(2000),
    source_media_ids    varchar(1000),
    valid_from          timestamp(6),
    valid_until         timestamp(6),
    occurred_at         timestamp(6),
    ended_at            timestamp(6),
    last_confirmed_at   timestamp(6),
    last_used_at        timestamp(6),
    last_decision_at    timestamp(6),
    superseded_by_id    bigint,
    legacy_id           bigint,
    embedding           vector(1024),
    embedding_model     varchar(64),
    created_at          timestamp(6) not null,
    updated_at          timestamp(6) not null
);

-- ① 原 core → PROFILE（无条件注入）
insert into memory (kind, legacy_id, user_id, content, always_inject, status, importance, confidence, keywords,
                    source, source_type, source_message_ids, source_media_ids,
                    last_confirmed_at, last_used_at, last_decision_at, superseded_by_id, created_at, updated_at)
select 'PROFILE', id, user_id, content, true, coalesce(nullif(status, ''), 'ACTIVE'), importance, confidence, keywords,
       'extraction', source_type, source_message_ids, source_media_ids,
       last_confirmed_at, last_used_at, last_decision_at, superseded_by_id,
       coalesce(created_at, now()), coalesce(updated_at, now())
from user_core_memory;

-- ② 原 work → TASK
insert into memory (kind, legacy_id, user_id, content, always_inject, status, importance, confidence, priority, keywords,
                    source, source_type, source_message_ids, source_media_ids, valid_from, valid_until,
                    last_confirmed_at, last_used_at, last_decision_at, superseded_by_id, created_at, updated_at)
select 'TASK', id, user_id, content, false, coalesce(nullif(status, ''), 'ACTIVE'), importance, confidence, priority,
       keywords, coalesce(source, 'extraction'), source_type, source_message_ids, source_media_ids,
       valid_from, valid_until, last_confirmed_at, last_used_at, last_decision_at, superseded_by_id,
       coalesce(created_at, now()), coalesce(updated_at, now())
from user_work_memory;

-- ③ 原 episode → EXPERIENCE
insert into memory (kind, legacy_id, user_id, content, title, category, always_inject, status, importance, confidence,
                    keywords, source, source_type, source_message_ids, source_media_ids, occurred_at, ended_at,
                    last_confirmed_at, last_used_at, superseded_by_id, created_at, updated_at)
select 'EXPERIENCE', id, user_id, summary, title, episode_type, false, coalesce(nullif(status, ''), 'ACTIVE'),
       importance, confidence, keywords, 'extraction', source_type, source_message_ids, source_media_ids,
       occurred_at, ended_at, last_confirmed_at, last_used_at, superseded_by_id,
       coalesce(created_at, now()), coalesce(updated_at, now())
from episodic_memory;

-- ④ 回填"我替代了谁"的自引用（同 kind 内按老 id 找新 id）
update memory m
set superseded_by_id = n.id
from memory n
where m.superseded_by_id is not null
  and n.kind = m.kind
  and n.legacy_id = m.superseded_by_id;

alter table memory drop column legacy_id;

create index if not exists idx_memory_user_status on memory (user_id, status);
create index if not exists idx_memory_user_kind on memory (user_id, kind);
create index if not exists idx_memory_user_always on memory (user_id, always_inject);
create index if not exists idx_memory_embedding on memory using hnsw (embedding vector_cosine_ops);

-- 核对（搬迁前后应一一对应）：
-- select kind, count(*) from memory group by 1 order by 1;
-- select (select count(*) from user_core_memory) as core,
--        (select count(*) from user_work_memory) as work,
--        (select count(*) from episodic_memory) as episode;
-- select count(*) from memory where superseded_by_id is not null;
--
-- 回滚：drop table if exists memory;   （老表一条都没动，回退镜像即恢复原状）
