-- 记忆合并收尾（2026-09-19）：删掉三张老表
--
-- 前置：V16 已经把 `user_core_memory` / `user_work_memory` / `episodic_memory` 全量搬进 `memory`
-- （生产 29 + 65 + 19 = 113 行，逐项核对过；跨 kind 替代引用 0 条）。此后新代码只读写 `memory`，
-- 老表从 V16 那一刻起就是**只读快照**，没有任何写入路径。
--
-- ⚠️ **删完就不能"回退镜像即恢复"了**：老代码的实体映射的是这三张表，删掉之后回退到旧镜像会启动失败。
--    真要回退必须先从这个 dump 恢复：
--      `psql -f /root/wechat-agent-memory-legacy-backup-20260918.sql`
--      （删表当天会另存一份带日期的，见执行记录）
--
-- 回滚（重建空表结构、数据从 dump 里来）：本文件末尾注释里有三张表的 `create table` 语句。
--
-- 判定依据（删之前跑过）：
--   1) `memory` 行数 = 三张老表行数之和（按 kind 逐项相等）；
--   2) 每条老行都能在 `memory` 里按 (kind, content) 找到对应行，反之亦然；
--   3) 应用侧：`grep -r user_core_memory|user_work_memory|episodic_memory src/main/java` 已无命中
--      （实体/仓库/Service 都在 V16 那次重构里删掉了）。

begin;

drop table if exists user_core_memory;
drop table if exists user_work_memory;
drop table if exists episodic_memory;

commit;

-- 回滚用的表结构（从旧 schema 抄的，只在需要恢复 dump 时用得上）：
--
-- create table user_core_memory (confidence integer, importance integer, created_at timestamp(6),
--   id bigint generated by default as identity, last_confirmed_at timestamp(6), last_decision_at timestamp(6),
--   last_used_at timestamp(6), superseded_by_id bigint, updated_at timestamp(6), source_type varchar(32),
--   status varchar(32), user_id varchar(128), keywords varchar(1000), source_media_ids varchar(1000),
--   source_message_ids varchar(2000), content varchar(4000), primary key (id));
--
-- create table user_work_memory (confidence integer, importance integer, priority integer, created_at timestamp(6),
--   id bigint generated by default as identity, last_confirmed_at timestamp(6), last_decision_at timestamp(6),
--   last_used_at timestamp(6), superseded_by_id bigint, updated_at timestamp(6), valid_from timestamp(6),
--   valid_until timestamp(6), source varchar(32), source_type varchar(32), status varchar(32), user_id varchar(128),
--   keywords varchar(1000), source_media_ids varchar(1000), content varchar(2000), source_message_ids varchar(2000),
--   primary key (id));
--
-- create table episodic_memory (confidence integer, importance integer, created_at timestamp(6), ended_at timestamp(6),
--   id bigint generated by default as identity, last_confirmed_at timestamp(6), last_used_at timestamp(6),
--   occurred_at timestamp(6), superseded_by_id bigint, updated_at timestamp(6), episode_type varchar(32) not null,
--   source_type varchar(32) not null, status varchar(32) not null, user_id varchar(128) not null,
--   title varchar(200) not null, keywords varchar(1000), source_media_ids varchar(1000),
--   source_message_ids varchar(2000), summary varchar(32600) not null, primary key (id));
