-- 每一次 LLM 调用的审计行（2026-09-21）：回答"最近到底花了多少钱、钱花在哪"。
--
-- 为什么还要这张表：现在只有 `memory_extraction_run` / `agent_quest_run` 两类**作业**按次记账，
-- 而对话本身（最大头，每轮一次流式调用）**只进了进程内计数**，重启归零、也无法按天/按场景聚合。
-- 这张表跟它们一样是"一行 = 一次调用"的账：命中/未命中分开算（命中价是未命中的 1/50）、
-- 峰谷 ×2 按调用时刻定，钱由 `LlmCostLedger.price(...)` 算好写进来。
--
-- 口径提醒：这张表按**调用**记（一轮对话可能有多次：正文 + 工具后继续），
-- 想让"一轮"的成本成组，看 `created_at` 的相邻秒数即可，不再单加轮次列。
--
-- ⚠️ 生产 `ddl-auto: validate`：**先在生产库执行本脚本，再部署镜像**。

create table if not exists llm_call_audit (
    id                 bigint generated by default as identity primary key,
    created_at         timestamp(6) not null,
    scenario           varchar(64)  not null,
    streaming          boolean      not null,
    ok                 boolean      not null,
    duration_ms        bigint       not null default 0,
    prompt_tokens      int          not null default 0,
    completion_tokens  int          not null default 0,
    reasoning_tokens   int          not null default 0,
    cache_hit_tokens   bigint       not null default 0,
    cache_miss_tokens  bigint       not null default 0,
    cost_yuan          numeric(10,4) not null default 0,
    error_message      varchar(200)
);

-- 按天/按场景聚合是主要用法（面板与我自己排查都走这个索引）
create index if not exists idx_llm_call_created on llm_call_audit (created_at desc);
create index if not exists idx_llm_call_scenario on llm_call_audit (scenario, created_at desc);

-- 常用查询（照抄即可）：
--   select created_at::date d, count(*), round(sum(cost_yuan)::numeric,4) yuan,
--          sum(prompt_tokens), sum(completion_tokens), sum(cache_hit_tokens), sum(cache_miss_tokens)
--     from llm_call_audit group by 1 order by 1;
--   select scenario, count(*), round(sum(cost_yuan)::numeric,4) yuan,
--          round(avg(prompt_tokens)::numeric,0) avg_prompt,
--          round(100.0*sum(cache_hit_tokens)/nullif(sum(prompt_tokens),0),1) hit_pct
--     from llm_call_audit group by 1 order by 3 desc;
