CREATE TABLE IF NOT EXISTS episodic_memory (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(128) NOT NULL,
    title VARCHAR(200) NOT NULL,
    summary LONGTEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    episode_type VARCHAR(32) NOT NULL,
    importance INT,
    confidence INT,
    source_type VARCHAR(32) NOT NULL DEFAULT 'USER_DERIVED',
    keywords VARCHAR(1000),
    occurred_at DATETIME(6),
    ended_at DATETIME(6),
    last_confirmed_at DATETIME(6),
    last_used_at DATETIME(6),
    superseded_by_id BIGINT,
    source_message_ids VARCHAR(2000),
    source_media_ids VARCHAR(1000),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    PRIMARY KEY (id),
    INDEX idx_episode_user_occurred (user_id, occurred_at),
    INDEX idx_episode_user_status (user_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
